### ISSUE TITLE
Overly constrained peerDependencies

### ISSUE THREAD

**Issue by cdaringe** [rescriptbr/react-query#1]
# Problem

React 18 is fine with react-query, but peerDeps suggest precise versions are needed here: https://github.com/rescriptbr/react-query/blob/master/package.json#L19-L20

# Discussion

Recommend to use a looser peerDependency semver range. e.g. `>=17`

**Comment by vmarcosp** [comment]
oh, thanks for reporting! I'll update the peerDeps field.

**Comment by vmarcosp** [comment]
v0.0.2 just released with the correct peerDependencies. Please let me know if you need something.
